name: Deploy
env: 
    EB_PACKAGE_S3_BUCKET_NAME : "a"
    EB_APPLICATION_NAME: "BackNodeJs"
    EB_ENVIROMENT_NAME: "BackNodeJs-env"
    DEPLOY_PACKAGE_NAME: "node_app_${{ github.sha }}.zip"
    AWS_REGION_NAME: "eu-north-1"

'on': 
    push: 
        branches:
            -master

jobs:
    my_ci_part:
        runs-on: ubuntu-latest
        steps:
        - name: Git clone our repo
            uses: actions/checkout@v2
        
        - name: Create Zip deploy package
            run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git