name: Deploy
env: 
    EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-eu-north-1-018113552303"
    EB_APPLICATION_NAME: "BackNodeJs"
    EB_ENVIROMENT_NAME: "BackNodeJs-env"
    DEPLOY_PACKAGE_NAME: "node_app_${{ github.sha }}.zip"
    AWS_REGION_NAME: "eu-north-1"

'on': 
    push: 
        branches:
            - main

jobs:
    my_ci_part:
        runs-on: ubuntu-latest
        steps:
        -   name: Git clone our repo
            uses: actions/checkout@v2
            
        -   name: Create Zip deploy package
            run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

        -   name: Configure my cred AWS
            uses: aws-action/configure-aws-credentials@v1
            with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION_NAME }}
        -   name: Copy Deployment package to S3 butcket 
            run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}
        
        -   name: Print Success Message for CI finish
            run: echo "Deploy pipline Finished successefully"